### ISSUE TITLE
react@19 compat: typecheck fails with 6 pre-existing TS errors (bigint in ReactNode, onToggle vs ToggleEventHandler)

### ISSUE THREAD

**Issue by usetheodev** [usetheokit/theokit-ui#45]
## Impact

`pnpm typecheck` fails under React 19 with **6 errors**, so the `react@19 compat` job in `quality-gates.yml` has never been green. `peerDependencies` already declares `"react": ">=18.2.0 <20"`, which numerically permits 19 — consumers on React 19 are inside our declared support range and will hit these on their own typecheck.

The job is `continue-on-error: true` and its comment states the intent: *"we gather evidence first, then decide whether to promote it to a required check."* This issue is that evidence. It is filed, not fixed, because the fix is a public-API decision (see § Suggested fix).

## Severity

**Medium.** Type-level only — no runtime failure is proven here (the `Test against React 19` step never runs, because the job stops at typecheck). But it blocks promoting the job to a required check, and it silently degrades the experience of every consumer inside our own declared peer range.

## Build under test

- Repo `usetheokit/theokit-ui`, branch `workspace` at `66fa11d`
- Package `@theokit/ui@1.4.1`
- Baseline peers: `react@18.3.1`, `@types/react@18.3.28`; job overrides to `react@^19` + `@types/react@^19`

## Repro

1. `pnpm install --frozen-lockfile`
2. `pnpm add -D react@^19 react-dom@^19 @types/react@^19 @types/react-dom@^19`
3. `pnpm typecheck`

Exits 2. Reproduced on every run of the job; the six errors are byte-for-byte identical across runs weeks apart (see § Evidence).

## Evidence

Two classes, six errors.

**A — `bigint` entered React 19's `ReactNode` union (5 errors).** `@types/react@19` widened `ReactNode` to include `bigint`; the components pass a value typed against the narrower React 18 `ReactNode` into a `Label` whose prop resolves to the React 19 one.

| File | Line |
|---|---|
| `src/components/composites/choice-prompt/choice-prompt.tsx` | 226 |
| `src/components/composites/multi-select-prompt/multi-select-prompt.tsx` | 219 |
| `src/components/composites/permission-modal/permission-modal.tsx` | 129, 130 |
| `src/components/composites/text-prompt/text-prompt.tsx` | 120 |

```
error TS2322: Type 'string | number | bigint | boolean | ReactElement<...> | Iterable<ReactNode> | Promise<...> | null'
  is not assignable to type 'ReactNode'.
  Type 'bigint' is not assignable to type 'ReactNode'.
```

`text-prompt.tsx:120` names both sides explicitly and is the clearest read — it resolves the target through `node_modules/.pnpm/@types+react@18.3.28`, i.e. **two copies of `@types/react` in one tree**. That points at the override step producing a mixed install rather than at our source, and is worth confirming before treating all five as source defects.

**B — `onToggle` now collides with a native DOM handler (1 error).** React 19's `HTMLAttributes` gained `onToggle?: ToggleEventHandler<T>` (the HTML `toggle` event, from `<details>`/popover). `ChannelCardProps` extends `HTMLAttributes<HTMLElement>` and redeclares `onToggle` with an incompatible domain signature.

`src/components/primitives/channel-card/channel-card.tsx:59` (interface) / `:62` (the prop):

```ts
onToggle?: (id: string, enabled: boolean) => void;
```

```
error TS2430: Interface 'ChannelCardProps' incorrectly extends interface 'HTMLAttributes<HTMLElement>'.
  Types of property 'onToggle' are incompatible.
    Target signature provides too few arguments. Expected 2 or more, but got 1.
```

## Not a regression from #44

Confirmed by diffing the failing-error sets of two runs:

- [run 32034950769](https://github.com/usetheokit/theokit-ui/actions/runs/32034950769) — 2026-08-17, `develop` PR, before the branch existed
- [run 32489423063](https://github.com/usetheokit/theokit-ui/actions/runs/32489423063) — 2026-08-21, PR #44

Identical: same six errors, same files, same line numbers. PR #44 introduces none of them.

## Suggested fix

**Class B is unambiguous and cheap.** `ChannelCardProps` should either drop the `HTMLAttributes` extension it conflicts with, or `Omit<HTMLAttributes<HTMLElement>, "onToggle">`. `Omit` is the smaller change and preserves the spread at `:75`. It is a **breaking type change for anyone passing a native `onToggle`** — nobody can be, since the current declaration already shadows it.

**Class A needs a measurement first, not a patch.** Before changing five components, confirm whether the errors survive a *clean* React 19 install rather than the `pnpm add -D` override over a React 18 lockfile. The `@types+react@18.3.28` path in the `text-prompt` message suggests both copies are present, and a duplicated `@types/react` produces exactly this shape of error without anything being wrong in our source. If a clean install is green, the defect is in the CI job's install strategy, not in the components — and patching the components would be treating a symptom that does not exist for consumers.

## Scope / sub-issues

- Class B (`channel-card`) can be fixed on its own and closes 1 of 6.
- Class A should be split out once the clean-install question is answered.
- Promoting `react@19 compat` to a required check is the closing criterion for both, and should not happen before then.

## Related

- PR #44 (where this was surfaced; carries no fix)
- `.github/workflows/quality-gates.yml`, job `react-19-compat` — introduced under "T6.3 (agent-team-audit-fixes plan)"

---

*How this was found:* reviewing CI on PR #44, which turned `quality:gates` green and left this job red. Verified pre-existing by comparing failing-error sets across two runs four days apart. No secrets in this report.

**Comment by usetheodev** [comment]
Fixed in `21db94c` — but the finding inverts what I wrote when filing this. I was wrong to leave the two-copies question as a caveat; measured, it is the whole story of five of the six errors, and it was hiding worse.

**The 5 `bigint` errors are not source defects.** The job's `pnpm add -D react@^19 …` bumps root dependencies and leaves every transitive peer where the lockfile put it, so `@usetheo/ui` kept `@types/react@18`. Measured:

```console
$ pnpm add -D react@^19 react-dom@^19 @types/react@^19 @types/react-dom@^19
$ ls -d node_modules/.pnpm/@types+react@*
node_modules/.pnpm/@types+react@18.3.28
node_modules/.pnpm/@types+react@19.2.18
```

Two copies means two `ReactNode` unions, and every value crossing between them fails to assign. The `text-prompt` error naming `@types+react@18.3.28` as its *target* was the tell.

**They were also masking the real ones.** Installed coherently — `pnpm.overrides` across the whole graph, verified down to a single copy — the same commit reports **24 errors, not 6**:

- **21 × `Cannot find namespace 'JSX'`.** React 19's types dropped the global JSX namespace, and 13 files used `JSX.Element` without importing it. Four files here already did it correctly (`import type { JSX } from "react"`, valid on both majors); the other 13 now match.
- **1 × the `onToggle` collision** — the one real error in the original six. Now `Omit<HTMLAttributes<HTMLElement>, "onToggle">`.
- **2 × the `components` map** handed to `toJsxRuntime`, whose value union tightened. Our public prop is `Record<string, unknown>` and cannot become `Partial<Components>`: `hast-util-to-jsx-runtime` is an **optional** peer, so naming its types in our public API would make them required for consumers who never render markdown. Cast at that boundary with the reason written there.

`tsc --noEmit` on a coherent React 19 tree goes **24 → 0**. React 18 stays 0; 1505 tests pass.

So the job was **under-reporting** incompatibility while appearing to over-report it. The workflow now sets `pnpm.overrides` before installing and asserts exactly one copy of `@types/react` before typechecking, failing with a message saying that any error past that point would be an install artifact rather than a React 19 finding. A job that cannot tell those apart is worse than no job.

**It stays `continue-on-error` for now**, and the reason is new information: with types fixed it gets far enough to run the suite for the first time, where **2 of 1500 tests fail** — `SlideDeck`'s async markdown parse never resolving under React 19. Ruled out the markdown stack (`splitDeck` works standalone there) and a Testing Library mismatch (16.3.2, officially React 19). Filed as **#48**; that is the remaining blocker to promoting this to a required check, which was the stated purpose of the job.
